package dev.porchlight.app.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import dev.porchlight.app.R

// ---------------------------------------------------------------------------
// Type — Inter, bundled in res/font (OFL, see licenses/Inter-OFL.txt).
//
// `Inter` is the text face; `InterDisplay` is the optical-size variant used
// for large/emphasized copy (screen titles, contact names, badges, the
// Call/Delete-style emphasized action text) where the tighter spacing reads
// as more confident. Sizes/weights/letter-spacing below come from
// `GeneratedType` (generated by Style Dictionary from the shared tokens/
// source, kept in sync with the web client) — which *FontFamily object*
// each role uses can't be expressed as a token (no way for a token to
// reference an `R.font` resource), so that mapping stays hand-written here,
// same as it was before this migration.
// ---------------------------------------------------------------------------

val Inter = FontFamily(
    Font(R.font.inter_regular, FontWeight.Normal),
    Font(R.font.inter_medium, FontWeight.Medium),
    Font(R.font.inter_semibold, FontWeight.SemiBold),
    Font(R.font.inter_bold, FontWeight.Bold),
)

val InterDisplay = FontFamily(
    Font(R.font.inter_display_semibold, FontWeight.SemiBold),
    Font(R.font.inter_display_bold, FontWeight.Bold),
)

/**
 * Named semantic text styles, sourced from the generated token scale.
 * Prefer these over inline `fontSize =` overrides so the scale stays
 * consistent — they read like the design spec, not magic numbers.
 */
object Type {
    val display = TextStyle(
        fontFamily = InterDisplay,
        fontWeight = FontWeight(GeneratedType.typographyDisplayFontWeight),
        fontSize = GeneratedType.typographyDisplayFontSize,
        letterSpacing = GeneratedType.typographyDisplayLetterSpacing,
    )
    val body = TextStyle(
        fontFamily = Inter,
        fontWeight = FontWeight(GeneratedType.typographyBodyFontWeight),
        fontSize = GeneratedType.typographyBodyFontSize,
    )
    val caption = TextStyle(
        fontFamily = Inter,
        fontWeight = FontWeight(GeneratedType.typographyCaptionFontWeight),
        fontSize = GeneratedType.typographyCaptionFontSize,
    )
    // Small toggle-switch labels (CallToggle's Audio/Video, WaitingScreen's
    // Auto-answer) — a dedicated role, not a reuse of `caption`, so these
    // can be pinned to their own smaller size independent of everything
    // else `caption` also styles.
    val statusRow = TextStyle(
        fontFamily = Inter,
        fontWeight = FontWeight(GeneratedType.typographyStatusRowFontWeight),
        fontSize = GeneratedType.typographyStatusRowFontSize,
    )
    val contactName = TextStyle(
        fontFamily = InterDisplay,
        fontWeight = FontWeight(GeneratedType.typographyContactNameFontWeight),
        fontSize = GeneratedType.typographyContactNameFontSize,
        letterSpacing = GeneratedType.typographyContactNameLetterSpacing,
    )
    val badge = TextStyle(
        fontFamily = InterDisplay,
        fontWeight = FontWeight(GeneratedType.typographyBadgeFontWeight),
        fontSize = GeneratedType.typographyBadgeFontSize,
        letterSpacing = GeneratedType.typographyBadgeLetterSpacing,
    )
    // New role, not carried over from before this migration — this is the
    // fix for the discovered bug where bare TvButton { Text(...) } call
    // sites (Continue, Contacts, Back, ...) fell through to Material3's own
    // default labelLarge instead of the app's Inter styling. Plain Inter
    // (not InterDisplay), matching the web client's `.tv-button` rule,
    // which has no display-optical face to draw on either.
    val buttonDefault = TextStyle(
        fontFamily = Inter,
        fontWeight = FontWeight(GeneratedType.typographyButtonDefaultFontWeight),
        fontSize = GeneratedType.typographyButtonDefaultFontSize,
    )
}

/** Material3 Typography so MaterialTheme.typography defaults to Inter too. */
val PorchlightTypography = Typography(
    headlineSmall = Type.display,
    bodyMedium = Type.caption,
    labelLarge = Type.buttonDefault,
)

/** Same shape, for the nested tv.material3.MaterialTheme — see Theme.kt. */
val PorchlightTvTypography = androidx.tv.material3.Typography(
    headlineSmall = Type.display,
    bodyMedium = Type.caption,
    labelLarge = Type.buttonDefault,
)
