package dev.porchlight.app

// Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.

object GeneratedSharedConfig {
    val RELAYS: List<String> = listOf(
        "wss://relay.primal.net",
        "wss://relay.snort.social",
        "wss://nostr-pub.wellorder.net",
        "wss://nostr.mom",
        "wss://nostr.oxtr.dev",
        "wss://nostr.data.haus",
        "wss://relay.damus.io",
        "wss://nos.lol",
    )

    val STUN_SERVERS: List<String> = listOf(
        "stun:stun.l.google.com:19302",
        "stun:stun1.l.google.com:19302",
    )

    const val AUTO_DISMISS_DELAY_MS: Long = 20_000L

    /** How often the presence-timeout / call-timeout / publish-retry sweep runs. */
    const val PRESENCE_TICK_INTERVAL_MS: Long = 10_000L

    /** Minimum gap between two re-subscribes after a relay closes our subscription. */
    const val SUBSCRIPTION_RESUBSCRIBE_COOLDOWN_MS: Long = 10_000L

    /** Cycle order of the self-view position, as wire names (see PreviewCorner). */
    val PREVIEW_POSITIONS: List<String> = listOf(
        "bottom-start",
        "top-start",
        "top-end",
        "bottom-end",
        "invisible",
    )
}
