package dev.porchlight.app

// Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.

object GeneratedSharedConfig {
    /** Version of the relay list built in; a fetched list with a higher version replaces it. */
    const val RELAYS_VERSION: Int = 3

    val RELAYS: List<String> = listOf(
        "wss://relay.chorus.community",
        "wss://relay.cyberguy.fyi",
        "wss://relay.pyramid.li",
        "wss://nostr-01.uid.ovh",
        "wss://relay.bullishbounty.com",
    )

    val STUN_SERVERS: List<String> = listOf(
        "stun:stun.l.google.com:19302",
        "stun:stun1.l.google.com:19302",
    )

    const val AUTO_DISMISS_DELAY_MS: Long = 20_000L

    /** How often the presence-timeout / call-timeout / publish-retry sweep runs. */
    const val PRESENCE_TICK_INTERVAL_MS: Long = 10_000L

    /** Minimum gap between two re-subscribes after a relay closes our subscription. */
    const val SUBSCRIPTION_RESUBSCRIBE_COOLDOWN_MS: Long = 10_000L

    /** Gap between the heartbeats to successive contacts, so a relay isn't hit by a burst. */
    const val HEARTBEAT_SPREAD_MS: Long = 400L

    /** How long the self-view takes to shrink to its corner when a call connects. */
    const val SELF_VIEW_SHRINK_MS: Int = 600

    /** How long a page may stay hidden, with nothing going on, before it disconnects from the relays. */
    const val PAUSE_WHEN_HIDDEN_MS: Long = 30_000L

    /** Longest pairing phrase the input accepts. */
    const val MAX_PHRASE_LENGTH: Int = 200

    /** Camera capture the call asks for. */
    const val CAPTURE_WIDTH: Int = 1280
    const val CAPTURE_HEIGHT: Int = 720
    const val CAPTURE_FPS: Int = 30

    /** Cycle order of the self-view position, as wire names (see PreviewCorner). */
    val PREVIEW_POSITIONS: List<String> = listOf(
        "bottom-start",
        "top-start",
        "top-end",
        "bottom-end",
        "invisible",
    )
}
