package dev.porchlight.app

// Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.

object GeneratedSharedConfig {
    val RELAYS: List<String> = listOf(
        "wss://relay.damus.io",
        "wss://nos.lol",
        "wss://relay.primal.net",
        "wss://relay.snort.social",
        "wss://offchain.pub",
    )

    val STUN_SERVERS: List<String> = listOf(
        "stun:stun.l.google.com:19302",
        "stun:stun1.l.google.com:19302",
    )

    const val AUTO_DISMISS_DELAY_MS: Long = 20_000L

    /** Cycle order of the self-view position, as wire names (see PreviewCorner). */
    val PREVIEW_POSITIONS: List<String> = listOf(
        "bottom-start",
        "top-start",
        "top-end",
        "bottom-end",
        "invisible",
    )
}
