// Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.

// Version of the relay list built in; a fetched list with a higher version replaces it.
export const RELAYS_VERSION = 2;

export const RELAYS = [
  "wss://relay.chorus.community",
  "wss://relay.cyberguy.fyi",
  "wss://relay.pyramid.li",
  "wss://nostr-01.uid.ovh",
  "wss://relay.bullishbounty.com"
];

export const STUN_SERVERS = [
  "stun:stun.l.google.com:19302",
  "stun:stun1.l.google.com:19302"
];

export const AUTO_DISMISS_DELAY_MS = 20000;

// How often the presence-timeout / call-timeout / publish-retry sweep runs.
export const PRESENCE_TICK_INTERVAL_MS = 10000;

// Minimum gap between two re-subscribes after a relay closes our subscription.
export const SUBSCRIPTION_RESUBSCRIBE_COOLDOWN_MS = 10000;

// Gap between the heartbeats to successive contacts, so a relay isn't hit by a burst.
export const HEARTBEAT_SPREAD_MS = 400;

// How long the self-view takes to shrink to its corner when a call connects.
export const SELF_VIEW_SHRINK_MS = 600;

// How long a page may stay hidden, with nothing going on, before it disconnects from the relays.
export const PAUSE_WHEN_HIDDEN_MS = 30000;

// Longest pairing phrase the input accepts.
export const MAX_PHRASE_LENGTH = 200;

// Camera capture the call asks for.
export const CAPTURE = {"width":1280,"height":720,"fps":30};

// Cycle order of the self-view position.
export const PREVIEW_POSITIONS = ["bottom-start","top-start","top-end","bottom-end","invisible"];
