// Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.

export const RELAYS = [
  "wss://relay.damus.io",
  "wss://nos.lol",
  "wss://relay.primal.net",
  "wss://relay.snort.social",
  "wss://offchain.pub"
];

export const STUN_SERVERS = [
  "stun:stun.l.google.com:19302",
  "stun:stun1.l.google.com:19302"
];

export const AUTO_DISMISS_DELAY_MS = 20000;

// Cycle order of the self-view position.
export const PREVIEW_POSITIONS = ["bottom-start","top-start","top-end","bottom-end","invisible"];
