#!/usr/bin/env node
// Generates android-app's GeneratedSharedConfig.kt and web-app's
// shared-config.js from shared/shared-config.json — the static values both
// clients must agree on (the relay list, STUN servers, how long a passive
// outcome screen stays up, the self-view position cycle). A small standalone
// script like build-strings.mjs, not a style-dictionary pass: these aren't
// design tokens. Both outputs are committed; rerun `npm run build:shared`
// after editing the JSON.
//
// Validates before writing: relay URLs must be wss://, STUN URLs stun:/stuns:,
// no duplicates, a positive dismiss delay, and a non-empty position cycle —
// so a typo fails here instead of as a silent runtime misbehavior on one
// platform.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(here, '..');
const cfg = JSON.parse(readFileSync(path.join(here, 'shared', 'shared-config.json'), 'utf8'));

function fail(message) {
  console.error(`shared-config.json: ${message}`);
  process.exit(1);
}
function checkList(name, list, pattern) {
  if (!Array.isArray(list) || list.length === 0) fail(`${name} must be a non-empty array`);
  for (const item of list) if (typeof item !== 'string' || !pattern.test(item)) fail(`${name} has an invalid entry: ${JSON.stringify(item)}`);
  if (new Set(list).size !== list.length) fail(`${name} has duplicates`);
}
checkList('relays', cfg.relays, /^wss:\/\/[a-z0-9.-]+(:\d+)?(\/.*)?$/i);
checkList('stunServers', cfg.stunServers, /^stuns?:[a-z0-9.-]+(:\d+)?$/i);
checkList('previewPositions', cfg.previewPositions, /^[a-z]+(-[a-z]+)?$/);
if (!Number.isInteger(cfg.autoDismissDelayMs) || cfg.autoDismissDelayMs <= 0) fail('autoDismissDelayMs must be a positive integer');

const q = (s) => JSON.stringify(s);
const header = 'Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.';

const kotlin = `package dev.porchlight.app

// ${header}

object GeneratedSharedConfig {
    val RELAYS: List<String> = listOf(
${cfg.relays.map((r) => `        ${q(r)},`).join('\n')}
    )

    val STUN_SERVERS: List<String> = listOf(
${cfg.stunServers.map((r) => `        ${q(r)},`).join('\n')}
    )

    const val AUTO_DISMISS_DELAY_MS: Long = ${String(cfg.autoDismissDelayMs).replace(/\B(?=(\d{3})+(?!\d))/g, '_')}L

    /** Cycle order of the self-view position, as wire names (see PreviewCorner). */
    val PREVIEW_POSITIONS: List<String> = listOf(
${cfg.previewPositions.map((r) => `        ${q(r)},`).join('\n')}
    )
}
`;

const js = `// ${header}

export const RELAYS = ${JSON.stringify(cfg.relays, null, 2)};

export const STUN_SERVERS = ${JSON.stringify(cfg.stunServers, null, 2)};

export const AUTO_DISMISS_DELAY_MS = ${cfg.autoDismissDelayMs};

// Cycle order of the self-view position.
export const PREVIEW_POSITIONS = ${JSON.stringify(cfg.previewPositions)};
`;

writeFileSync(path.join(repoRoot, 'android-app/app/src/main/java/dev/porchlight/app/GeneratedSharedConfig.kt'), kotlin);
writeFileSync(path.join(repoRoot, 'web-app/shared-config.js'), js);
console.log('wrote GeneratedSharedConfig.kt and shared-config.js');
