#!/usr/bin/env node
// Generates android-app's res/values[-<locale>]/strings.xml and web-app's
// strings.js from the locale files in tokens/strings/ (en.json today; a
// future de.json etc. needs no code change here — just adding the file and
// rerunning `npm run build:strings` picks it up). Deliberately not run
// through style-dictionary like the design tokens are — natural-language
// strings need positional-placeholder handling (see below) that's outside
// what a design-token pipeline is for, so this is a small standalone script
// instead.
//
// Placeholder convention: {name}-style in the source JSON, positional in
// the order each one first appears in that language's own text — the
// Android XML output turns them into %1$s/%2$s/... in that same order, and
// web's strings.js keeps the {name} form for a runtime .replace(). This
// means a translated string is free to reorder a sentence's clauses (a
// real difference between languages) as long as every {placeholder} that
// appears in English still appears somewhere in the translation — the
// numbering follows each language's own order, not English's.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const stringsDir = path.join(here, 'strings');
const repoRoot = path.join(here, '..');

function flatten(obj, prefix = '', out = {}) {
  for (const [key, value] of Object.entries(obj)) {
    if (key === '_comment') continue;
    const flatKey = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      flatten(value, flatKey, out);
    } else {
      out[flatKey] = String(value);
    }
  }
  return out;
}

function androidResourceName(flatKey) {
  return flatKey.replace(/\./g, '_');
}

/** Replaces every distinct {placeholder} with Android's %1$s/%2$s/... , in
 * the order each one first appears in this specific string. */
function toAndroidPlaceholders(text) {
  const seen = [];
  return text.replace(/\{(\w+)\}/g, (_, name) => {
    let index = seen.indexOf(name);
    if (index === -1) { seen.push(name); index = seen.length - 1; }
    return `%${index + 1}$s`;
  });
}

function escapeAndroidXmlText(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"');
}

function buildAndroidXml(flat) {
  const lines = ['<resources>'];
  for (const [key, text] of Object.entries(flat)) {
    const name = androidResourceName(key);
    const escaped = escapeAndroidXmlText(toAndroidPlaceholders(text));
    lines.push(`    <string name="${name}">${escaped}</string>`);
  }
  lines.push('</resources>');
  return lines.join('\n') + '\n';
}

function localesFromDir() {
  return readdirSync(stringsDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort((a, b) => (a === 'en' ? -1 : b === 'en' ? 1 : a.localeCompare(b)));
}

function buildAndroid(locales, flatByLocale) {
  for (const locale of locales) {
    const dir = locale === 'en'
      ? path.join(repoRoot, 'android-app/app/src/main/res/values')
      : path.join(repoRoot, `android-app/app/src/main/res/values-${locale}`);
    mkdirSync(dir, { recursive: true });
    const xml = buildAndroidXml(flatByLocale[locale]);
    writeFileSync(path.join(dir, 'strings.xml'), xml);
  }
}

function buildWeb(locales, flatByLocale) {
  const out = [
    '// AUTO-GENERATED by tokens/build-strings.mjs from tokens/strings/*.json — do not edit directly.',
    '',
    'export const STRINGS = ' + JSON.stringify(flatByLocale, null, 2) + ';',
    '',
    "export const DEFAULT_LOCALE = 'en';",
    '',
    '/** Nearest supported locale for a BCP-47 tag like "de-DE" — exact match',
    ' * first, then just the language part, then DEFAULT_LOCALE. */',
    'export function resolveLocale(tag) {',
    '  if (STRINGS[tag]) return tag;',
    "  const lang = (tag || '').split('-')[0];",
    '  if (STRINGS[lang]) return lang;',
    '  return DEFAULT_LOCALE;',
    '}',
    '',
    '/** key: a dotted path like "settings.kioskMode.title". params: an',
    ' * object whose keys match the {placeholder} names in that string.',
    ' * Falls back to DEFAULT_LOCALE, then to the bare key, if missing —',
    ' * never throws, so a locale file that lags behind English degrades to',
    ' * readable (English) text instead of a blank UI. */',
    'export function t(locale, key, params) {',
    '  const text = (STRINGS[locale] && STRINGS[locale][key]) ?? STRINGS[DEFAULT_LOCALE][key] ?? key;',
    '  if (!params) return text;',
    '  return text.replace(/\\{(\\w+)\\}/g, (_, name) => (name in params ? String(params[name]) : `{${name}}`));',
    '}',
    '',
  ];
  writeFileSync(path.join(repoRoot, 'web-app/strings.js'), out.join('\n'));
}

const locales = localesFromDir();
const flatByLocale = {};
for (const locale of locales) {
  const raw = JSON.parse(readFileSync(path.join(stringsDir, `${locale}.json`), 'utf8'));
  flatByLocale[locale] = flatten(raw);
}

buildAndroid(locales, flatByLocale);
buildWeb(locales, flatByLocale);

console.log(`strings\n✔︎ ${locales.length === 1 ? '1 locale' : locales.length + ' locales'} (${locales.join(', ')}) → android-app res/values*/strings.xml, web-app/strings.js`);
