#!/usr/bin/env node
// Generates android-app's GeneratedSharedConfig.kt and web-app's
// shared-config.js from shared/shared-config.json — the static values both
// clients must agree on (the relay list, STUN servers, how long a passive
// outcome screen stays up, the self-view position cycle). A small standalone
// script like build-strings.mjs, not a style-dictionary pass: these aren't
// design tokens. Both outputs are committed; rerun `npm run build:shared`
// after editing the JSON.
//
// Validates before writing: relay URLs must be wss://, STUN URLs stun:/stuns:,
// no duplicates, positive timings, and a non-empty position cycle — so a typo
// fails here instead of as a silent runtime misbehavior on one platform. Also
// fails if SECURITY.md (which names every relay a user's traffic touches)
// doesn't mention one of them, so the doc can't silently drift from the list.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(here, '..');
const cfg = JSON.parse(readFileSync(path.join(here, 'shared', 'shared-config.json'), 'utf8'));

function fail(message) {
  console.error(`shared-config.json: ${message}`);
  process.exit(1);
}
function checkList(name, list, pattern) {
  if (!Array.isArray(list) || list.length === 0) fail(`${name} must be a non-empty array`);
  for (const item of list) if (typeof item !== 'string' || !pattern.test(item)) fail(`${name} has an invalid entry: ${JSON.stringify(item)}`);
  if (new Set(list).size !== list.length) fail(`${name} has duplicates`);
}
checkList('relays', cfg.relays, /^wss:\/\/[a-z0-9.-]+(:\d+)?(\/.*)?$/i);
checkList('stunServers', cfg.stunServers, /^stuns?:[a-z0-9.-]+(:\d+)?$/i);
checkList('previewPositions', cfg.previewPositions, /^[a-z]+(-[a-z]+)?$/);
for (const key of ['autoDismissDelayMs', 'presenceTickIntervalMs', 'subscriptionResubscribeCooldownMs', 'heartbeatSpreadMs', 'selfViewShrinkMs', 'maxPhraseLength', 'pauseWhenHiddenMs']) {
  if (!Number.isInteger(cfg[key]) || cfg[key] <= 0) fail(`${key} must be a positive integer`);
}
for (const key of ['width', 'height', 'fps']) {
  if (!cfg.capture || !Number.isInteger(cfg.capture[key]) || cfg.capture[key] <= 0) fail(`capture.${key} must be a positive integer`);
}
const securityDoc = readFileSync(path.join(repoRoot, 'SECURITY.md'), 'utf8');
for (const relay of cfg.relays) {
  const host = new URL(relay).hostname;
  if (!securityDoc.includes(host)) fail(`SECURITY.md doesn't mention relay ${host} — update its list of relays to match`);
}

// The web client's Content-Security-Policy only lets it open sockets to hosts it lists.
const webHtml = readFileSync(path.join(repoRoot, 'web-app', 'index.html'), 'utf8');
const csp = (webHtml.match(/http-equiv="Content-Security-Policy"\s+content="([^"]*)"/) || [, ''])[1];
const connectSrc = (csp.match(/connect-src([^;]*)/) || [, ''])[1].split(/\s+/);
if (!csp) fail("couldn't find the Content-Security-Policy meta tag in web-app/index.html");
for (const relay of cfg.relays) {
  if (!connectSrc.includes(relay)) fail(`web-app/index.html's Content-Security-Policy connect-src doesn't allow ${relay} — add it`);
}

const q = (s) => JSON.stringify(s);
const kotlinMs = (n) => `${String(n).replace(/\B(?=(\d{3})+(?!\d))/g, '_')}L`;
const header = 'Generated by tokens/build-shared.mjs from tokens/shared/shared-config.json — do not edit by hand; edit the JSON and run `npm run build:shared`.';

const kotlin = `package dev.porchlight.app

// ${header}

object GeneratedSharedConfig {
    val RELAYS: List<String> = listOf(
${cfg.relays.map((r) => `        ${q(r)},`).join('\n')}
    )

    val STUN_SERVERS: List<String> = listOf(
${cfg.stunServers.map((r) => `        ${q(r)},`).join('\n')}
    )

    const val AUTO_DISMISS_DELAY_MS: Long = ${kotlinMs(cfg.autoDismissDelayMs)}

    /** How often the presence-timeout / call-timeout / publish-retry sweep runs. */
    const val PRESENCE_TICK_INTERVAL_MS: Long = ${kotlinMs(cfg.presenceTickIntervalMs)}

    /** Minimum gap between two re-subscribes after a relay closes our subscription. */
    const val SUBSCRIPTION_RESUBSCRIBE_COOLDOWN_MS: Long = ${kotlinMs(cfg.subscriptionResubscribeCooldownMs)}

    /** Gap between the heartbeats to successive contacts, so a relay isn't hit by a burst. */
    const val HEARTBEAT_SPREAD_MS: Long = ${kotlinMs(cfg.heartbeatSpreadMs)}

    /** How long the self-view takes to shrink to its corner when a call connects. */
    const val SELF_VIEW_SHRINK_MS: Int = ${cfg.selfViewShrinkMs}

    /** How long a page may stay hidden, with nothing going on, before it disconnects from the relays. */
    const val PAUSE_WHEN_HIDDEN_MS: Long = ${kotlinMs(cfg.pauseWhenHiddenMs)}

    /** Longest pairing phrase the input accepts. */
    const val MAX_PHRASE_LENGTH: Int = ${cfg.maxPhraseLength}

    /** Camera capture the call asks for. */
    const val CAPTURE_WIDTH: Int = ${cfg.capture.width}
    const val CAPTURE_HEIGHT: Int = ${cfg.capture.height}
    const val CAPTURE_FPS: Int = ${cfg.capture.fps}

    /** Cycle order of the self-view position, as wire names (see PreviewCorner). */
    val PREVIEW_POSITIONS: List<String> = listOf(
${cfg.previewPositions.map((r) => `        ${q(r)},`).join('\n')}
    )
}
`;

const js = `// ${header}

export const RELAYS = ${JSON.stringify(cfg.relays, null, 2)};

export const STUN_SERVERS = ${JSON.stringify(cfg.stunServers, null, 2)};

export const AUTO_DISMISS_DELAY_MS = ${cfg.autoDismissDelayMs};

// How often the presence-timeout / call-timeout / publish-retry sweep runs.
export const PRESENCE_TICK_INTERVAL_MS = ${cfg.presenceTickIntervalMs};

// Minimum gap between two re-subscribes after a relay closes our subscription.
export const SUBSCRIPTION_RESUBSCRIBE_COOLDOWN_MS = ${cfg.subscriptionResubscribeCooldownMs};

// Gap between the heartbeats to successive contacts, so a relay isn't hit by a burst.
export const HEARTBEAT_SPREAD_MS = ${cfg.heartbeatSpreadMs};

// How long the self-view takes to shrink to its corner when a call connects.
export const SELF_VIEW_SHRINK_MS = ${cfg.selfViewShrinkMs};

// How long a page may stay hidden, with nothing going on, before it disconnects from the relays.
export const PAUSE_WHEN_HIDDEN_MS = ${cfg.pauseWhenHiddenMs};

// Longest pairing phrase the input accepts.
export const MAX_PHRASE_LENGTH = ${cfg.maxPhraseLength};

// Camera capture the call asks for.
export const CAPTURE = ${JSON.stringify(cfg.capture)};

// Cycle order of the self-view position.
export const PREVIEW_POSITIONS = ${JSON.stringify(cfg.previewPositions)};
`;

writeFileSync(path.join(repoRoot, 'android-app/app/src/main/java/dev/porchlight/app/GeneratedSharedConfig.kt'), kotlin);
writeFileSync(path.join(repoRoot, 'web-app/shared-config.js'), js);
console.log('wrote GeneratedSharedConfig.kt and shared-config.js');
